### ISSUE TITLE
getting error while instantiate

### ISSUE THREAD

**Issue by abhi141** [CosmWasm/cw-plus#738] opened 2022-06-17 10:12 UTC
` wasmd tx wasm i 1480  '{"name":"DIZZ COIN", "symbol":"DIZZ", "decimals":6, "initial_balances":[ { "address":"8CEBE444C05DEB7035EF81E11EB098E71AA8CC67", "amount":"1000000" } ], "mint":{ "minter":"8CEBE444C05DEB7035EF81E11EB098E71AA8CC67", "cap":"999000000"},"students_info":{"first_name":"testing","age":0}}' --label "CW201" --no-admin --from "wasm1s7l2yc43l39vjfe2ca48xnfket9arvvgypkcd5" --node "https://rpc.cliffnet.cosmwasm.com:443" --chain-id "cliffnet-1" --fees "700000upebble" $TXFLAG --gas auto --gas-adjustment 1.2`

the above was the command used and iam getting th below error
`Error: rpc error: code = InvalidArgument desc = failed to execute message; message index: 0: Error parsing into type cw20_base::msg::InstantiateMsg: Invalid type: instantiate wasm contract failed: invalid request`

please help me out,thanks in advance

**Comment by ethanfrey** [comment] 2022-06-20 21:01
> pub age:Uint128

This must be encoded as a string. It is outside of safe json int range.

use `"age": "0"`

**Comment by abhi141** [comment] 2022-06-21 05:00
`wasmd tx wasm instantiate 1480  '{"name":"DIZZ COIN", "symbol":"DIZZ", "decimals":6, "initial_balances":[ { "address":"wasm1saa8w4dy77p0yn5yl28m4mca9xhnrysstwv879", "amount":"1000000" } ], "mint":{ "minter":"wasm1saa8w4dy77p0yn5yl28m4mca9xhnrysstwv879", "cap":"99900000000" },"students_info":{"first_name":"test","age":"0"}}' --label "CW20" --no-admin --from "wasm174ka7k0qtnfksvpu9mutreulylap3vc928qmrx" --node "https://rpc.cliffnet.cosmwasm.com:443" --chain-id "cliffnet-1" --fees "700000upebble" --gas auto $TXFLAG`

got executed tx hash is `A1674D575E9299B902641A7ABE6B9E937346D2B307FAD1B20816282625535DBD`
`BB459765431C1EDF093A27E852AE84ADB40A3AFF304375AA202173EEABE46A69`

But still iam not getting any result for list-contract-by-code 1480

`wasmd query wasm list-contract-by-code 1480 --node "https://rpc.cliffnet.cosmwasm.com:443" --output json | jq -s`

```
query result
[
  {
    "contracts": [],
    "pagination": {
      "next_key": null,
      "total": "0"
    }
  }
]
```

for contract instantiation i got the hash ,but still its not reflecting in list-contract-code

pls let me know where iam going wrong

@ethanfrey @hashedone @shanev @alpe

**Comment by hashedone** [comment] 2022-06-21 08:30
Honestly - I cannot reproduce your problem. I just executed:
```
$ wasmd tx wasm instantiate 1480 '{"name":"DIZZ COIN", "symbol":"DIZZ", "decimals":6, "initial_balances":[ { "address":"wasm1wukxp2kldxae36rgjz28umqtq792twtxdfe6ux", "amount":"1000000" } ], "mint":{ "minter":"wasm1wukxp2kldxae36rgjz28umqtq792twtxdfe6ux", "cap":"99900000000" },"students_info":{"first_name":"test","age":"0"}}' --from wallet --label "Group" --no-admin $TXFLAG -y
```
and contract is created:
```
$ wasmd query wasm list-contract-by-code 1480 --node "https://rpc.cliffnet.cosmwasm.com:443" --output json | jq -s
[
  {
    "contracts": [
      "wasm13cxsumf5gn0zwh5whntnzvfl5ryv04492aqhs02dtx7dpd0arq3qvh5k98"
    ],
    "pagination": {
      "next_key": null,
      "total": "0"
    }
  }
]
```
Same for execution a bit more similar to yours:
```
$ wasmd tx wasm instantiate 1480 '{"name":"DIZZ COIN", "symbol":"DIZZ", "decimals":6, "initial_balances":[ { "address":"wasm1wukxp2kldxae36rgjz28umqtq792twtxdfe6ux", "amount":"1000000" } ], "mint":{ "minter":"wasm1wukxp2kldxae36rgjz28umqtq792twtxdfe6ux", "cap":"99900000000" },"students_info":{"first_name":"test","age":"0"}}' --label "CW20" --no-admin --from wallet --node "https://rpc.cliffnet.cosmwasm.com:443" --chain-id "cliffnet-1" --gas auto $TXFLAG
...
$ wasmd query wasm list-contract-by-code 1480 --node "https://rpc.cliffnet.cosmwasm.com:443" --output json | jq -s
[
  {
    "contracts": [
      "wasm13cxsumf5gn0zwh5whntnzvfl5ryv04492aqhs02dtx7dpd0arq3qvh5k98",
      "wasm120hajldhzthg5f847wymn43ped58e4qcn79a85rqvd78prguyqxq66cdqg"
    ],
    "pagination": {
      "next_key": null,
      "total": "0"
    }
  }
]
```
I had to remove `--fees` flag because in my `$TXFLAG` I have `--gas-prices` which collide with each other. My `$TXFLAG`:
```
$ echo $TXFLAG
--node https://rpc.cliffnet.cosmwasm.com:443 --chain-id cliffnet-1 --gas-prices 0.025upebble --gas-adjustment 1.3 --gas auto -b block
```

One thing which comes to my mind is - do you use `-b block`? In general, it is not recommended to use it, but without it, the response is received before it is actually delivered and committed to blocking. If anything fails after CheckTx, you will not get an error. In particular - if you do have not enough tokens to pay gas, I believe you will not get an error (it would just silently fail), while with `-b block` you get an "out of gas" response. Obviously, you can try to make sure that you have enough pebbles and so but still it may be something else I don't see.

Also - it is not recommended to use `cliffnet-1` anymore, it may be decommissioned at any moment use `malaga-420` if you can: https://github.com/CosmWasm/testnets/tree/master/malaga-420. You can find setup instructions in the CosmWasm book: https://book.cosmwasm.com/wasmd-quick-start/testnet.html (also docs.cosmwasm.com is already updated to use malaga network).

Another nitpick - do you think you need `Uint128` for age? I would be surprise if any students outlive `u8` range, unless it is in days ;)

**Closed** 2022-08-08 08:55 UTC
Labels: wontfix
